sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
    - autoconf
    - automake
    - autopoint
    - autotools-dev
    - bison
    - docbook-utils
    - docbook-xml
    - docbook-xsl
    - flex
    - ghostscript
    - gir1.2-freedesktop
    - gir1.2-glib-2.0
    - gobject-introspection
    - gtk-doc-tools
    - iso-codes
    - jade
    - libaa1-dev
    - libasound2-dev
    - libbz2-dev
    - libcaca-dev
    - libcairo2-dev
    - libcap-dev
    - libcdparanoia-dev
    - libdv4-dev
    - libflac-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgmp3-dev
    - libgsl0-dev
    - libgtk-3-dev
    - libgudev-1.0-dev
    - libiec61883-dev
    - libjack-jackd2-dev
    - libjpeg-dev
    - libopus-dev
    - libpango1.0-dev
    - libpng-dev
    - libpulse-dev
    - libraw1394-dev
    - libshout3-dev
    - libsoup2.4-dev
    - libspeex-dev
    - libtag1-dev
    - libtool
    - libv4l-dev
    - libvisual-0.4-dev
    - libvorbis-dev
    - libvpx-dev
    - libwavpack-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxt-dev
    - libxv-dev
    - netpbm
    - pkg-config
    - python
    - texlive-generic-recommended
    - transfig
    - xmlto
    - xsltproc
    - zlib1g-dev

